In [29]:
import numpy as np

a = np.array([[1,2,3],
              [4,5,6]])

print(a.shape) #order of matrix
print(a.size)
print(a.dtype)

(2, 3)
6
int64


In [55]:
np.empty(5)


array([2.12199579e-314, 4.67296746e-307, 2.88534337e-321, 6.95187041e-310,
       2.10080983e-312])

In [51]:
np.ones(17)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [52]:
np.zeros(4)

array([0., 0., 0., 0.])

In [59]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])


In [60]:
np.concatenate((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
arr = np.array([[ 1,  2,  3,  4,  5],[ 6,  7,  8,  9, 10]])
print(arr[1,-1])

10


In [69]:
arr = np.array([ 1,  2,  3,  4,  5])
x = arr.view()
arr[0]= 100

print(arr)
print(x)

[100   2   3   4   5]
[100   2   3   4   5]


In [74]:
arr = np.array([ 1,  2,  3,  4,  5, 6])
new_arr = arr.reshape(2,3)
print(new_arr)

[[1 2 3]
 [4 5 6]]


In [79]:
arr = np.array([[ 1,  2,  3,  4,  5],[ 6,  7,  8,  9, 10],[ 6,  7,  8,  9, 10]])
new_arr = arr.reshape(-1)
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10  6  7  8  9 10]


In [85]:
import numpy as np

arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


# Class task

In [100]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11])
b = np.zeros(5)
c = np.array ([1,1,1,1,1,1,1,1,1])
new_arr = c.reshape(3,3)
arr = np.linspace(0, 1, 6)

print()
print(a)
print()
print(b)
print()
print(new_arr)
print()
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11]

[0. 0. 0. 0. 0.]

[[1 1 1]
 [1 1 1]
 [1 1 1]]

[0.  0.2 0.4 0.6 0.8 1. ]


In [113]:
import numpy as np

arr = np.array([
                [1, 9, 3, 7, 5, 6],
                [1, 2, 3, 4, 5, 6]
              ])

print(np.cumsum(arr))
print(np.cumprod(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.argsort(arr))

[ 1 10 13 20 25 31 32 34 37 41 46 52]
[      1       9      27     189     945    5670    5670   11340   34020
  136080  680400 4082400]
0
1
[[0 2 4 5 3 1]
 [0 1 2 3 4 5]]
